### ISSUE TITLE
SSG should fail when it receives 0 bytes

### ISSUE THREAD

**Issue by sriniketh923** [jhunt/ssg#21]
Currently, ssg creates a zero byte archive. I was thinking that it would be better if the 0 byte archives are deleted.

Scenario 1:
When the ssg seems that no data has been written on eof, it can send an error back to the caller and delete the archive. (seems like the ideal solution)

Scenario 2:
The SHIELD agent can see that no data was backed up and throw an error. When the ssg does a sweep, it can clear out any 0 byte archives that it sees.

Scenario 3:
The SHIELD agent can see that no data was backed up and throw an error. Then a purge should be done on the 0 byte archive. (this seems a little more messy?)

**Comment by jhunt** [comment]
I agree with the assessment; SSG should signal an error if someone tries to upload an empty file.  The empty file is the empty file, so having the ability to store multiple versions of the empty files is weird at best, and wasteful at worst.

If, when the last (EOF) segment is seen, SSG notices that it has written 0 (uncompressed) bytes total, it should cancel the upload and return a 400 Bad Request response to the caller.  The payload should indicate that the upload failed because the uploaded file was empty.
